//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriBoschProfiles
    {
        public string Ansteuerprofil { get; set; }
        public short UB { get; set; }
        public int UC { get; set; }
        public short IBoost { get; set; }
        public short IAnzug { get; set; }
        public short IAnzugTol { get; set; }
        public short IHalte { get; set; }
        public short IHalteTol { get; set; }
        public short LA { get; set; }
        public short LH { get; set; }
        public short TAnzug { get; set; }
        public short TMinHalte { get; set; }
        public short Abschaltmode { get; set; }
    }
}
