//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriPruefschritte
    {
        public int CriPruefschrittID { get; set; }
        public string TypTeileNr { get; set; }
        public string PruefschrittNr { get; set; }
        public string Pruefschrittname { get; set; }
        public string Ansteuerdauer { get; set; }
        public string Arbeitsdruck { get; set; }
        public string Einspritzmenge { get; set; }
        public string EinspritzmengeToleranz { get; set; }
        public string Ruecklaufmenge { get; set; }
        public string RuecklaufmengeToleranz { get; set; }
        public string Messzeit { get; set; }
        public string IsMengenmessung { get; set; }
        public string EPM { get; set; }
    }
}
