//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DhkKomponenten
    {
        public int DhkID { get; set; }
        public string TypTeileNr { get; set; }
        public string Beschreibung { get; set; }
        public string Hersteller { get; set; }
        public bool IsBoschData { get; set; }
        public System.DateTime Aktualisiert { get; set; }
        public System.DateTime Erstellt { get; set; }
        public float Oeffnungsdruck1_Min { get; set; }
        public float Oeffnungsdruck1_Max { get; set; }
        public bool Oeffnungsdruck2_Testen { get; set; }
        public Nullable<float> Oeffnungsdruck2_Min { get; set; }
        public Nullable<float> Oeffnungsdruck2_Max { get; set; }
        public bool Schnarrpruefung_Testen { get; set; }
        public bool Kombinationsdichtheit_Testen { get; set; }
        public bool Sitzdichtheit_Testen { get; set; }
        public bool Strahlbild_Testen { get; set; }
        public Nullable<float> Kombinationsdichtheit { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
