//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protokolle
    {
        public int ProtokollID { get; set; }
        public Nullable<System.DateTime> Pruefdatum { get; set; }
        public string KundenName { get; set; }
        public string KundenNr { get; set; }
        public string KomponentenTyp { get; set; }
        public string TypTeileNr { get; set; }
        public string Pruefer { get; set; }
        public byte[] Ergebnisprotokoll { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
